language: java

jdk:
  - oraclejdk7
  
branches:
  only:
    - master

env:
  global:
    - secure: "pmNBqCAW1rc4WKHEmnroZNwAMus18K1VWhRYwt+CN0acH8griJp612tjwWcI\n9XkZcSPR0CJx1TZqGDZZTFH44Pkm6ELU1kc54xtJR6WMXnubEVoEom0tcv/1\nNyzxv9UFJfaNgaTESww+OXSlO9wQre5ZS0/wn2xrz0+twtOPYDU="
    - secure: "CZ9mejMLJdrh+a5TFXsNSiYyK9K/zNYOtubv2sPq1OEGhuohdUfLtdsk7bK9\nQcIlhZjrE5Q/wVgjZcFsnVpKhnUSRLC7sTOh6tu08EwpNtnNLl5AeUztOMCs\nxhG5H7jDu9uEH81WDZnIuK4Zq4qxXx523rnqQfk4DsTCKLVh9jI="
    - secure: "X2K6U964Tf46CrytIhOE74W70vsOgMF+OetHapgOb7yr7qmEth0YCjO5cts7\nOOCvl/VCw3hIIoPNeCZpw1cy+wcA5FhT0pBX8l7NQIPw4HoRhYmdaDHVwKU8\nFO/BtJkYcV2on+yrCJaqfaF6BMasfNdCCSTtloVlDwHxqRHFr40="

script: mvn clean install

before_install:
  - git submodule update --init --recursive

after_success:
  - mvn -Pcobertura -DserviceName=travis-ci -DserviceJobId=$TRAVIS_JOB_ID -Dbranch=$TRAVIS_BRANCH clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:cobertura
  - grep '\-SNAPSHOT</version>' pom.xml && python etc/travis-sonatype.py && mvn -Pprepare-deploy clean deploy --settings ~/.m2/sonatype.xml
